import "./ui/globals.css";
import { geistSans, geistMono } from "./ui/fonts";
import Sidebar from "./ui/components/Sidebar";

export const metadata = {
  title: "Athon Dashboard",
  description: "Generated by pablodev",
  icons: './athonfav.png'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex">
          <Sidebar />

          <div className="p-10">
              {children}
          </div>
        </div>
      </body>
    </html >
  );
}
